unit TestBufferInterpreter.NVMe;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, BufferInterpreter.NVMe, SysUtils, BufferInterpreter,
  Device.SMART.List, MeasureUnit.DataSize;

type
  // Test methods for class TNVMeBufferInterpreter

  TestTNVMeBufferInterpreter = class(TTestCase)
  strict private
    FNVMeBufferInterpreter: TNVMeBufferInterpreter;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestBufferToIdentifyDeviceResult;
    procedure TestBufferToSMARTValueList;
    procedure TestLargeBufferToIdentifyDeviceResult;
    procedure TestLargeBufferToSMARTValueList;
    procedure TestBufferToCapacityAndLBA;
  end;

implementation

procedure TestTNVMeBufferInterpreter.SetUp;
begin
  FNVMeBufferInterpreter := TNVMeBufferInterpreter.Create;
end;

procedure TestTNVMeBufferInterpreter.TearDown;
begin
  FNVMeBufferInterpreter.Free;
  FNVMeBufferInterpreter := nil;
end;

procedure TestTNVMeBufferInterpreter.TestBufferToIdentifyDeviceResult;
var
  ReturnValue: TIdentifyDeviceResult;
  Buffer: TSmallBuffer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FNVMeBufferInterpreter.BufferToIdentifyDeviceResult(Buffer);
  // TODO: Validate method results
end;

procedure TestTNVMeBufferInterpreter.TestBufferToSMARTValueList;
var
  ReturnValue: TSMARTValueList;
  Buffer: TSmallBuffer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FNVMeBufferInterpreter.BufferToSMARTValueList(Buffer);
  // TODO: Validate method results
end;

procedure TestTNVMeBufferInterpreter.TestLargeBufferToIdentifyDeviceResult;
var
  ReturnValue: TIdentifyDeviceResult;
  Buffer: TLargeBuffer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FNVMeBufferInterpreter.LargeBufferToIdentifyDeviceResult(Buffer);
  // TODO: Validate method results
end;

procedure TestTNVMeBufferInterpreter.TestLargeBufferToSMARTValueList;
var
  ReturnValue: TSMARTValueList;
  Buffer: TLargeBuffer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FNVMeBufferInterpreter.LargeBufferToSMARTValueList(Buffer);
  // TODO: Validate method results
end;

procedure TestTNVMeBufferInterpreter.TestBufferToCapacityAndLBA;
var
  ReturnValue: TIdentifyDeviceResult;
  Buffer: TSmallBuffer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FNVMeBufferInterpreter.BufferToCapacityAndLBA(Buffer);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTNVMeBufferInterpreter.Suite);
end.

