unit TestBufferInterpreter.SCSI;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, BufferInterpreter.SCSI, Device.SMART.List, SysUtils,
  BufferInterpreter;

type
  // Test methods for class TSCSIBufferInterpreter

  TestTSCSIBufferInterpreter = class(TTestCase)
  strict private
    FSCSIBufferInterpreter: TSCSIBufferInterpreter;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestBufferToIdentifyDeviceResult;
    procedure TestBufferToSMARTValueList;
    procedure TestLargeBufferToIdentifyDeviceResult;
    procedure TestLargeBufferToSMARTValueList;
  end;

implementation

procedure TestTSCSIBufferInterpreter.SetUp;
begin
  FSCSIBufferInterpreter := TSCSIBufferInterpreter.Create;
end;

procedure TestTSCSIBufferInterpreter.TearDown;
begin
  FSCSIBufferInterpreter.Free;
  FSCSIBufferInterpreter := nil;
end;

procedure TestTSCSIBufferInterpreter.TestBufferToIdentifyDeviceResult;
var
  ReturnValue: TIdentifyDeviceResult;
  Buffer: TSmallBuffer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FSCSIBufferInterpreter.BufferToIdentifyDeviceResult(Buffer);
  // TODO: Validate method results
end;

procedure TestTSCSIBufferInterpreter.TestBufferToSMARTValueList;
var
  ReturnValue: TSMARTValueList;
  Buffer: TSmallBuffer;
begin
  StartExpectingException(ENotSupportedException);
  ReturnValue :=
    FSCSIBufferInterpreter.BufferToSMARTValueList(Buffer);
  StopExpectingException;
end;

procedure TestTSCSIBufferInterpreter.TestLargeBufferToIdentifyDeviceResult;
var
  ReturnValue: TIdentifyDeviceResult;
  Buffer: TLargeBuffer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FSCSIBufferInterpreter.LargeBufferToIdentifyDeviceResult(Buffer);
  // TODO: Validate method results
end;

procedure TestTSCSIBufferInterpreter.TestLargeBufferToSMARTValueList;
var
  ReturnValue: TSMARTValueList;
  Buffer: TLargeBuffer;
begin
  StartExpectingException(ENotSupportedException);
  ReturnValue :=
    FSCSIBufferInterpreter.LargeBufferToSMARTValueList(Buffer);
  StopExpectingException;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSCSIBufferInterpreter.Suite);
end.

