unit TestThread.Trim.Helper.Partition;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, OS.ProcessOpener, Thread.Trim.Helper.Partition.OS, SysUtils,
  Thread.Trim.Helper.Partition;

type
  // Test methods for class TOSPartitionTrimmer

  TestTOSPartitionTrimmer = class(TTestCase)
  strict private
    FOSPartitionTrimmer: TOSPartitionTrimmer;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestParseProgress;
  end;

implementation

const
  DriveOptimizerString83: String =
    'Microsoft Drive Optimizer'#$D#$A +
    'Copyright (c) 2013 Microsoft Corp.'#$D#$A#$D#$A +
    '다시 잘라내기(Windows (C:)) 호출 중...'#$D#$D#$A#$D#$A#$D#$A +
    '1 단계를 수행하는 중'#$D#$A#$D#9 +
    '다시 잘라내기:  0% 완료...'#$D#9 +
    '다시 잘라내기:  57% 완료...'#$D#9 +
    '다시 잘라내기:  58% 완료...'#$D#9 +
    '다시 잘라내기:  69% 완료...'#$D#9 +
    '다시 잘라내기:  71% 완료...'#$D#9 +
    '다시 잘라내기:  72% 완료...'#$D#9 +
    '다시 잘라내기:  83% 완료...'#$D#9;

  DriveOptimizerString100: String =
    'Microsoft Drive Optimizer'#$D#$A +
    'Copyright (c) 2013 Microsoft Corp.'#$D#$A#$D#$A +
    '다시 잘라내기(Windows (C:)) 호출 중...'#$D#$D#$A#$D#$A#$D#$A +
    '1 단계를 수행하는 중'#$D#$A#$D#9 +
    '다시 잘라내기:  0% 완료...'#$D#9 +
    '다시 잘라내기:  57% 완료...'#$D#9 +
    '다시 잘라내기:  58% 완료...'#$D#9 +
    '다시 잘라내기:  69% 완료...'#$D#9 +
    '다시 잘라내기:  71% 완료...'#$D#9 +
    '다시 잘라내기:  72% 완료...'#$D#9 +
    '다시 잘라내기:  83% 완료...'#$D#9 +
    '다시 잘라내기:  93% 완료...'#$D#9 +
    '다시 잘라내기:  100% 완료.  '#$D#$A#$D#$A +
    '작업을 완료했습니다.'#$D#$A#$D#$A +
    'Post Defragmentation Report:'#$D#$A#$D#$D#$A#9 +
    '볼륨 정보:'#$D#$A#9#9 +
    '볼륨 크기                 = 111.34 GB'#$D#$A#9#9 +
    '사';

procedure TestTOSPartitionTrimmer.SetUp;
begin
  FOSPartitionTrimmer := TOSPartitionTrimmer.Create('');
end;

procedure TestTOSPartitionTrimmer.TearDown;
begin
  FOSPartitionTrimmer.Free;
  FOSPartitionTrimmer := nil;
end;

procedure TestTOSPartitionTrimmer.TestParseProgress;
begin
  FOSPartitionTrimmer.ParseProgress(DriveOptimizerString83);
  CheckEquals(83, FOSPartitionTrimmer.Progress);
  FOSPartitionTrimmer.ParseProgress(DriveOptimizerString100);
  CheckEquals(100, FOSPartitionTrimmer.Progress);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTOSPartitionTrimmer.Suite);
end.

