unit TestSecurityDescriptorManipulator;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, OS.SecurityDescriptor;

type
  // Test methods for class TSCSIBufferInterpreter

  TestTSecurityDescriptorManipulator = class(TTestCase)
  public
    FSecurityDescriptorManipulator: TWriteBufferSettingVerifier;
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSecurityDescriptor;
  end;

implementation

procedure TestTSecurityDescriptorManipulator.SetUp;
begin
  FSecurityDescriptorManipulator := TSecurityDescriptorManipulator.Create;
end;

procedure TestTSecurityDescriptorManipulator.TearDown;
begin
  FSecurityDescriptorManipulator.Free;
  FSecurityDescriptorManipulator := nil;
end;

procedure TestTSecurityDescriptorManipulator.TestSecurityDescriptor;
var
  TestResult: PSECURITY_DESCRIPTOR;
begin
  TestResult := FSecurityDescriptorManipulator.GetSecurityDescriptor;
  CheckEquals(true,
    CompareMem(TestResult, @ExpectedResult, SizeOf(SECURITY_DESCRIPTOR)),
    'Unexpected Security Descriptor');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSecurityDescriptorManipulator.Suite);
end.

