unit TestPartitionTrimmer;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,
  uPartitionTrimmer;

type
  // Test methods for class TPartitionTrimmer

  TestTPartitionTrimmer = class(TTestCase)
  strict private
    FPartitionTrimmer: TPartitionTrimmer;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTPartitionTrimmer.SetUp;
begin
  FPartitionTrimmer := TPartitionTrimmer.Create;
end;

procedure TestTPartitionTrimmer.TearDown;
begin
  FPartitionTrimmer.Free;
  FPartitionTrimmer := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTPartitionTrimmer.Suite);
end.

